plugins {
    id 'java'
    id 'io.github.reyerizo.gradle.jcstress' version '0.8.15'
}

group = 'dev.tommyjs'
version = '2.5.5'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation project(':futur-api')
}

jcstress {
    jcstressDependency = 'org.openjdk.jcstress:jcstress-core:0.16'
}
